tasks:
  - name: AWS CLI
    init: npm install https://github.com/aws/aws-cli.git

ports:
  - port: 3000
    visibility: public
  - port: 4567
    visibility: public

vscode:
  extensions:
    - 42Crunch.vscode-openapi