tasks:
  - name: AWS CLI
    init: python -m pip install awscli

ports:
  - port: 3000
    visibility: public
  - port: 4567
    visibility: public

vscode:
  extensions:
    - 42Crunch.vscode-openapi