tasks:
  - name: aws cli
    init: python -m pip install awscli
    command: aws --version

ports:
  - port: 3000
    visibility: public
    onOpen: open-preview
    description: frontend
  - port: 4567
    visibility: public
    onOpen: open-preview
    description: backend

vscode:
  extensions:
    - 42Crunch.vscode-openapi